global:
  smtp_from: 'example@example.com'
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: 'example@example.com'
  smtp_auth_identity: 'example@example.com'
  smtp_auth_password: '0123456789abcdef'

route:
  # Fallback
  receiver: 'admin'
  group_wait: 40s
  group_interval: 5m
  repeat_interval: 30m
  routes:
    - match_re:
        app_type: (linux|windows)
      receiver: ss-admin
      routes:
        - match:
            app_type: linux
          receiver: linux-team-admin
          group_by:
            - category
          routes:
            - match:
                severity: critical
              receiver: linux-team-manager
            - match:
                severity: warning
              receiver: linux-team-lead
        - match:
            app_type: windows
          receiver: windows-team-admin
          routes:
            - match:
                severity: critical
              receiver: windows-team-manager
            - match:
                severity: warning
              receiver: windows-team-lead
    # PEC Technologies
    - match_re:
        app_type: (python|go)
      receiver: pec-admin
      routes:
        - match:
            app_type: python
          receiver: python-team-admin
          routes:
            - match:
                severity: critical
              receiver: python-team-manager
            - match:
                severity: warning
              receiver: python-team-lead
        - match:
            app_type: go
          receiver: go-team-admin
          routes:
            - match:
                severity: critical
              receiver: go-team-manager
            - match:
                severity: warning
              receiver: go-team-lead

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal:
      - app_type
      - category

receivers:
  - name: admin
    email_configs:
    - to: 'example@example.com'
  - name: ss-admin
    email_configs:
    - to: 'ss-admin@example.com'
  - name: linux-team-admin
    email_configs:
    - to: 'linux-team-admin@example.com'
  - name: linux-team-manager
    email_configs:
    - to: 'linux-team-manager@example.com'
  - name: linux-team-lead
    email_configs:
    - to: 'linux-team-lead@example.com'
  - name: windows-team-admin
    email_configs:
    - to: 'windows-team-admin@example.com'
  - name: windows-team-manager
    email_configs:
    - to: 'windows-team-manager@example.com'
  - name: windows-team-lead
    email_configs:
    - to: 'windows-team-lead@example.com'
  - name: pec-admin
    email_configs:
    - to: 'pec-admin@example.com'
  - name: python-team-admin
    email_configs:
    - to: 'python-team-admin@example.com'
  - name: python-team-manager
    email_configs:
    - to: 'python-team-manager@example.com'
  - name: python-team-lead
    email_configs:
    - to: 'python-team-lead@example.com'
  - name: go-team-admin
    email_configs:
    - to: 'go-team-admin@example.com'
  - name: go-team-manager
    email_configs:
    - to: 'go-team-manager@example.com'
  - name: go-team-lead
    email_configs:
    - to: 'go-team-lead@example.com'
