global:
  smtp_from: 'example@example.com'
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: 'example@example.com'
  smtp_auth_identity: 'example@example.com'
  smtp_auth_password: '0123456789abcdef'

route:
  # Fallback
  receiver: 'admin'
  routes:
    - match_re:
        app_type: (linux|windows)
      receiver: ss-admin
      routes:
        - match:
            app_type: linux
          receiver: linux-team-admin
          routes:
            - match:
                severity: critical
              receiver: linux-team-manager
            - match:
                severity: warning
              receiver: linux-team-lead
        - match:
            app_type: windows
          receiver: windows-team-admin
          routes:
            - match:
                severity: critical
              receiver: windows-team-manager
            - match:
                severity: warning
              receiver: windows-team-lead

receivers:
  - name: admin
    email_configs:
    - to: 'example@example.com'
  - name: ss-admin
    email_configs:
    - to: 'ss-admin@example.com'
  - name: linux-team-admin
    email_configs:
    - to: 'linux-team-admin@example.com'
  - name: linux-team-manager
    email_configs:
    - to: 'linux-team-manager@example.com'
  - name: linux-team-lead
    email_configs:
    - to: 'linux-team-lead@example.com'
  - name: windows-team-admin
    email_configs:
    - to: 'windows-team-admin@example.com'
  - name: windows-team-manager
    email_configs:
    - to: 'windows-team-manager@example.com'
  - name: windows-team-lead
    email_configs:
    - to: 'windows-team-lead@example.com'
