version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - prometheus
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
      - './prometheus/rules:/etc/prometheus/rules:ro'
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - 9100:9100
    networks:
      - prometheus
  # Python apps
  python_counter:
    build:
      context: client-python
      dockerfile: ./Dockerfile
    image: marchino/prometheus.python
    container_name: python_counter
    volumes:
      - './client-python:/usr/src/app:ro'
    command:
      - '/usr/src/app/counter.py'
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - prometheus
  python_gauge:
    image: marchino/prometheus.python
    container_name: python_gauge
    volumes:
      - './client-python:/usr/src/app:ro'
    command:
      - '/usr/src/app/gauge.py'
    ports:
      - 8010:8000
      - 8011:8001
    networks:
      - prometheus
  python_histogram:
    image: marchino/prometheus.python
    container_name: python_histogram
    volumes:
      - './client-python:/usr/src/app:ro'
    command:
      - '/usr/src/app/histogram.py'
    ports:
      - 8020:8000
      - 8021:8001
    networks:
      - prometheus
  python_summary:
    image: marchino/prometheus.python
    container_name: python_summary
    volumes:
      - './client-python:/usr/src/app:ro'
    command:
      - '/usr/src/app/summary.py'
    ports:
      - 8030:8000
      - 8031:8001
    networks:
      - prometheus
  # Go apps
  go_counter:
    build:
      context: client-go
      dockerfile: ./Dockerfile
    image: marchino/prometheus.go
    container_name: go_counter
    command:
      - '/app/counter'
    ports:
      - 8100:8000
      - 8101:8001
    networks:
      - prometheus
  go_gauge:
    image: marchino/prometheus.go
    container_name: go_gauge
    command:
      - '/app/gauge'
    ports:
      - 8110:8000
      - 8111:8001
    networks:
      - prometheus
  go_histogram:
    image: marchino/prometheus.go
    container_name: go_histogram
    command:
      - '/app//histogram'
    ports:
      - 8120:8000
      - 8121:8001
    networks:
      - prometheus
  go_summary:
    image: marchino/prometheus.go
    container_name: go_summary
    command:
      - '/app/summary'
    ports:
      - 8130:8000
      - 8131:8001
    networks:
      - prometheus
  
  # GRAFANA
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - prometheus
networks:
  prometheus:

