global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - "rules/*.yml"
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: node_exporter_wsl
  static_configs:
  - targets:
    - node_exporter:9100
- job_name: node_exporter_windows
  static_configs:
  - targets:
    - host.docker.internal:9182
- job_name: docker
  static_configs:
  - targets:
    - host.docker.internal:9323
- job_name: prom_python
  static_configs:
  - targets:
    - python_counter:8001
    - python_gauge:8001
    - python_histogram:8001
    - python_summary:8001
- job_name: prom_go
  static_configs:
  - targets:
    - go_counter:8000
    - go_gauge:8000
    - go_histogram:8000
    - go_summary:8000
