groups:
  - name: windows-rules
    rules:
      - alert: WindowsExporterDown
        expr: up{job="node_exporter_windows"} == 0
        for: 2m
        labels:
          severity: critical
          app_type: windows
          category: server
        annotations:
          summary: "Windows Exporter is down"
          description: "Windows Exporter is down for more than 2 minutes"
      - record: job:windows_physical_memory_bytes:free
        expr: (windows_os_physical_memory_free_bytes / windows_os_physical_memory_bytes) * 100
      - alert: WindowsMemoryUsageAbove60%
        expr: 60 < (100 - job:windows_physical_memory_bytes:available) < 75
        for: 2m
        labels:
          severity: warning
          app_type: windows
          category: memory
        annotations:
          summary: "Windows memory usage is going high"
          description: "Windows memory for instance {{ $labels.instance }} has reached {{ $value }}"
      - alert: WindowsMemoryUsageAbove75%
        expr: (100 - job:windows_physical_memory_bytes:available) >= 75
        for: 2m
        labels:
          severity: critical
          app_type: windows
          category: memory
        annotations:
          summary: "Windows memory usage is very HIGH"
          description: "Windows memory for instance {{ $labels.instance }} has reached {{ $value }}"
      - alert: WindowsCPUUsageHigh
        expr: 100 - (avg by(instance) (irate(windows_cpu_time_total{mode="idle"}[1m])) * 100) > 80
        for: 2m
        labels:
          severity: critical
          app_type: windows
          category: cpu
        annotations:
          summary: "Windows CPU usage is HIGH"
          description: "CPU load for instance {{ $labels.instance }} has reached {{ $value }}"
      - alert: WindowsFreeDiskSpaceUsageAbove80%
        expr: 100 - ((windows_logical_disk_free_bytes / windows_logical_disk_size_bytes) * 100) > 80
        for: 2m
        labels:
          severity: warning
          app_type: windows
          category: disk
        annotations:
          summary: "Windows disk space usaage is HIGH"
          description: "Windows disk usage is more than 80% with value = {{ $value }}"
